### PR TITLE
Corrected README

### PR DESCRIPTION
**Pull request by kahunacohen**
No need to release separate version for this, just corrections to README related to changes in how we handle sauce.

### CODE REVIEW

**Comment by hellmanj** [comment]
:thumbsup:

**Comment by frishberg** [comment]
:+1:

**Comment by kahunacohen** [comment]
Any idea why the master build broke when this was merged? Flaky tests?
https://travis-ci.org/ncbi/robotframework-pageobjects/builds/64564889

**Comment by frishberg** [comment]
Yeah, flaky tests. See https://github.com/ncbi/robotframework-pageobjects/pull/25#issuecomment-95746560 and https://github.com/ncbi/robotframework-pageobjects/compare/hide-not-remove

**Comment by kahunacohen** [comment]
Not sure from the ticket...was this flakiness addressed. or a fix not merged?

**Comment by frishberg** [comment]
I started addressing it in that branch, but haven't finished.

**Pull request merged**
