### PR TITLE
Add sauce option screen resolution.

### PR DESCRIPTION
**Pull request by tmonck**
I need the ability to change the screen resolution and thought that this might be handy for other people using this library.

### CODE REVIEW

**Comment by tmonck** [comment]
I noticed my PR failed on unit tests but it was a StaleElementException. Should I look into this and try and resolve the issue with the unit test?

Also should I update the documentation with these changes if you accept them

**Comment by frishberg** [comment]
Thank you for the pull request! It surprises me that your change would cause this failure. Can you try running the tests in your own dev environment and see if that one still fails?

**Comment by tmonck** [comment]
I am unable to get the  tests to run locally. I'm not sure why but I'm constantly getting unable to open phantomjs with ghostdriver. Is it possible for you to point me to where I'm potentially getting this error as I've commented out the portion of code where the exception appears to be coming from and I'm still receiving the exact same error.

**Comment by frishberg** [comment]
Sure. Do you have phantomjs installed locally? This may not be clear from the Readme, but you actually have to install phantomjs separately, and make sure it's on your PATH:
http://phantomjs.org/download.html

**Comment by tmonck** [comment]
I didn't have it in my Python Path. But I just made everything run through firefox while waiting. That gave me the same failure that is present with the build. I will add phantomjs to my path. I'm not sure how my modification could have caused the StaleElementException.

**Comment by frishberg** [comment]
> I'm not sure how my modification could have caused the StaleElementException.

Yeah, that's surprising. Did you try running the tests in master?

**Comment by tmonck** [comment]
I ran again locally and it did not throw the Exception. I also noticed that line that causes the exception changes. Almost like the page didn't load quick enough for the test.

**Comment by tmonck** [comment]
I tried master and my branch and now I can't get it to throw the StaleElementException. Not sure what happened there.

**Comment by frishberg** [comment]
Could be a problem that only happens sometimes. This could be hard to debug. We actually have a python script (I can give you a paste of the source if you like) that @kahunacohen wrote to debug stuff like this. You pass it a command, and it runs the command repeatedly, multiprocessed, until there's a failure or error. I just ran that script and got a failure on your master branch; I just ran it on ours and it failed there, too.

Looking at https://travis-ci.org/ncbi/robotframework-pageobjects/builds/59561738#L319, it shows that the error occured at https://github.com/ncbi/robotframework-pageobjects/blob/master/robotpageobjects/base.py#L861. That function, `_is_visible`, is defined in Selenium2Library, and fetches a `WebElement` object, then calls its `is_displayed()` method. So it *could* be that the element is removed after the `WebElement` object is fetched but before `is_displayed()` is called. Maybe?

In any event, I'm going to modify the test so that it hides the element instead of removing it. I'll submit a pull request.

Meanwhile, unless @kahunacohen or @hellmanj objects, I'll merge your pull request since the issues are unrelated.

**Comment by tmonck** [comment]
Thank you very much. Should I update the documentation about the sauce options to account for my modifications prior to you merging in the PR.

**Comment by frishberg** [comment]
> Should I update the documentation about the sauce options to account for my modifications prior to you merging in the PR.

Yes, please.

**Comment by frishberg** [comment]
@kahunacohen and @hellmanj, I've created https://github.com/ncbi/robotframework-pageobjects/tree/hide-not-remove for the other problem. It's not quite working yet, though.

**Comment by frishberg** [comment]
@tmonck, once you've updated the docs, I'll merge.

**Comment by tmonck** [comment]
Readme has been updated with the new sauce option.

**Comment by frishberg** [comment]
Great, thanks again for the contribution! Merged.

**Pull request merged**
