### PR TITLE
clean up how libdoc is generated a bit

### PR DESCRIPTION
**Pull request by hellmanj**

### CODE REVIEW

**Comment by frishberg** [comment]
Is this to prevent libdoc on components?

**Comment by hellmanj** [comment]
It was originally to take out the extraneous libdoc entries for aliases (see Get Hash On Page etc in http://ncbi.github.io/robotframework-pageobjects/) but then I was thinking the S2L wrappers we have there (like Location Should Be) are covered in the S2L docs as well, so maybe take them out too.  I was hoping for feedback about that point from you.  I could agree it's nice to have the documentation there which explicitly says how it's different from the original, but it's also cleaner and less distracting not to have them.

**Comment by hellmanj** [comment]
@frishberg and I decided to leave in the wrappers, but make it very clear in the docstring which I've done by bolding "wrapper" wherever it appears.

**Comment by frishberg** [comment]
Looks great to me.

**Pull request merged**
