### PR TITLE
Selectors with se2lib keywords

### PR DESCRIPTION
**Pull request by frishberg**
Instead of importing Se2Lib alongside the page class, we let the first page class that inherits from Se2Lib register Se2Lib's keywords. That way, we don't have to have this separate import, and our overridden `_element_find` is called when you call an Se2Lib keyword, which allows using selectors.

### CODE REVIEW

**Comment by kahunacohen** [comment]
Looks OK to me. It's getting a bit abstract for me to understand well at this point. Looks like there's a failing build though.

**Comment by kahunacohen** [comment]
Looks like we are taking two screenshots again :) And then there are some browser exited before..

**Comment by kahunacohen** [comment]
I upped the SE2lib version in requirements.txt.

**Comment by frishberg** [comment]
A different test failed because I was using `Open Browser` without specifying pjs. Just changed that.

**Comment by hellmanj** [comment]
Great!

**Comment by kahunacohen** [comment]
:+1:

**Pull request merged**
