### PR TITLE
Sauce listener

### PR DESCRIPTION
**Pull request by kahunacohen**
Made base page library a listener itself so that we can tag sauce jobs with test names and status.

### CODE REVIEW

**Comment by frishberg** [comment]
Looks great!

**Comment by hellmanj** [comment]
Cool, what about tests?  Is that what the new files at the top level are supposed to be?

**Comment by kahunacohen** [comment]
No those files shouldn't have been committed. I guess I should write tests ideally, but writing them for this is probably not worth it. It would be hard to mock up, and maybe not worth it. You can take a stab at it, but I really should be moving on...I'll remove those files.

**Comment by kahunacohen** [comment]
Can I merge?

**Comment by frishberg** [comment]
👍

**Comment by hellmanj** [comment]
ok

**Pull request merged**
