### PR TITLE
added sauce_device option

### PR DESCRIPTION
**Pull request by kahunacohen**
Added support for sauce_device option.

### CODE REVIEW

**Comment by hellmanj** [comment]
This should be probably be added as a "trigger" option here https://github.com/ncbi/robotframework-pageobjects/blob/master/robotpageobjects/page.py#L361

**Comment by kahunacohen** [comment]
@hellmanj yeah you're right. I'll add to this branch.

**Comment by kahunacohen** [comment]
OK added.

**Comment by kahunacohen** [comment]
Declining this PR. Merged this into another branch I am working on to fix some sauce issues.

**Pull request closed without merging**
