### PR TITLE
Added test for service args, took out old failing, complex test

### PR DESCRIPTION
**Pull request by kahunacohen**
Old test for service args was complex and hard to debug. This one is more of a unit test. It at least tests that when you set the option, the driver get's what it's supposed to. Also took out tests against www.ncbi since we don't want to make http requests against our site. Replaced them with tests against a file using file:// scheme.

### CODE REVIEW

**Comment by kahunacohen** [comment]
Yay, passing build!

**Comment by hellmanj** [comment]
Fantastic :)

**Comment by kahunacohen** [comment]
Shall I merge?

**Comment by hellmanj** [comment]
sure

**Pull request merged**
