### PR TITLE
Readmechanges

### PR DESCRIPTION
**Pull request by kahunacohen**
Emphasized simple use-cases without subclassing Page and pointed to demo README for more advanced use-case.

### CODE REVIEW

**Comment by hellmanj** [comment]
looks good

**Comment by kahunacohen** [comment]
Failing build...

**Comment by kahunacohen** [comment]
Build passes locally. unit tests, and function tests. Any idea what's up @hellmanj ?

**Comment by hellmanj** [comment]
We discussed and agreed that this flaky test will be rectified when selenium2library makes their next release which should be soon.

**Pull request merged**
