### PR TITLE
Fix for flaky tests

### PR DESCRIPTION
**Pull request by frishberg**
This has to do with tests that were discovered as flaky in https://github.com/ncbi/robotframework-pageobjects/pull/25. These are tests for keywords that check visibility, but they were using removal of page elements instead of hiding. This fixes that so the elements are hidden instead.

### CODE REVIEW

**Comment by kahunacohen** [comment]
:+1:

**Comment by hellmanj** [comment]
:+1:

**Comment by frishberg** [comment]
I don't think we need to bother tagging this, since it's only tests.

**Comment by kahunacohen** [comment]
Agreed

**Pull request merged**
